### ISSUE TITLE
Not found code using 'attrs' but it is required.

### ISSUE THREAD

**Issue by xiacunshun** [aio-libs/aiosmtpd#427] opened 2024-03-14 07:21 UTC
I wonder that 'attrs==23.2.0' in requirements.txt, but I can not see any where imporrt it?

**Comment by webknjaz** [comment] 2024-03-14 17:33
#341 suggested replacing it with stdlib dataclasses. Perhaps that's happened already. I suggest asking over there so there's no duplicates.

**Comment by webknjaz** [comment] 2024-03-14 17:33
Duplicate of #341

**Closed by webknjaz** 2024-03-14 17:33 UTC
